CC = gcc
CFLAGS = $(GLOBAL_CFLAGS) $(APP_CFLAGS) $(LINUX_CFLAGS)
CXXFLAGS = $(CFLAGS)
PLATFORM_OBJECTS = t3f/menu.o $(LINUX_PLATFORM_OBJECTS)
PLATFORM_LIBS = -lallegro_dialog$(LIB_SUFFIX) $(LINUX_PLATFORM_LIBS)
DEPEND_LIBS = -lm $(LINUX_DEPEND_LIBS)
DEL_COMMAND = rm -f
DEL_FOLDER_COMMAND = rm -rf
SED_COMMAND = sed -i
COPY_COMMAND = cp
PATH_SEPARATOR = /

include makefile.common

prepare_platform:
	@echo Ready to build...
